# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-23 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20170710_0907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infosource',
            options={'ordering': ('ordering', 'id'), 'verbose_name': "Source d'information", 'verbose_name_plural': "Source d'informations"},
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='club',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='instantpaymentnotification',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='instantpaymentnotification',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='license',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nom court'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='partners', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='club',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='N° de licence'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='payment_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='runner',
            name='scan',
            field=models.FileField(help_text='Joindre un scan de la license sportive ou du certificat médical. Merci de ne pas dépasser 2Mo comme taille de fichier.', upload_to='licenses', verbose_name='Fichier'),
        ),
    ]
